import phone from "phone";

export const FormRules = {
  required: [(v: string): string | boolean => !!v || "This field is required"],
  email: [
    (v: string): string | boolean =>
      /.+@.+/.test(v) || "Email address is invalid",
  ],
  phone: [
    (v: string): string | boolean =>
      phone(v, { country: "USA" }).isValid || "Phone number is invalid",
  ],
};

export const VisitStatuses = [
  { label: "Booked", value: "booked" },
  { label: "Assigned", value: "assigned" },
  { label: "Enroute", value: "enroute" },
  { label: "Started", value: "started" },
  { label: "Completed", value: "completed" },
  { label: "Canceled", value: "canceled" },
];

export const DaysOfWeek = [
  { label: "Sunday", value: 0 },
  { label: "Monday", value: 1 },
  { label: "Tuesday", value: 2 },
  { label: "Wednesday", value: 3 },
  { label: "Thursday", value: 4 },
  { label: "Friday", value: 5 },
  { label: "Saturday", value: 6 },
];

export const HoursOfDay = [
  { label: "12:00 AM", value: "24:00:00" },
  { label: "01:00 AM", value: "01:00:00" },
  { label: "02:00 AM", value: "02:00:00" },
  { label: "03:00 AM", value: "03:00:00" },
  { label: "04:00 AM", value: "04:00:00" },
  { label: "05:00 AM", value: "05:00:00" },
  { label: "06:00 AM", value: "06:00:00" },
  { label: "07:00 AM", value: "07:00:00" },
  { label: "08:00 AM", value: "08:00:00" },
  { label: "09:00 AM", value: "09:00:00" },
  { label: "10:00 AM", value: "10:00:00" },
  { label: "11:00 AM", value: "11:00:00" },
  { label: "12:00 PM", value: "12:00:00" },
  { label: "01:00 PM", value: "13:00:00" },
  { label: "02:00 PM", value: "14:00:00" },
  { label: "03:00 PM", value: "15:00:00" },
  { label: "04:00 PM", value: "16:00:00" },
  { label: "05:00 PM", value: "17:00:00" },
  { label: "06:00 PM", value: "18:00:00" },
  { label: "07:00 PM", value: "19:00:00" },
  { label: "08:00 PM", value: "20:00:00" },
  { label: "09:00 PM", value: "21:00:00" },
  { label: "10:00 PM", value: "22:00:00" },
  { label: "11:00 PM", value: "23:00:00" },
];

export const States = [
  { name: "Alabama", code: "AL" },
  { name: "Alaska", code: "AK" },
  { name: "Arizona", code: "AZ" },
  { name: "Arkansas", code: "AR" },
  { name: "California", code: "CA" },
  { name: "Colorado", code: "CO" },
  { name: "Connecticut", code: "CT" },
  { name: "Delaware", code: "DE" },
  { name: "District of Columbia", code: "DC" },
  { name: "Florida", code: "FL" },
  { name: "Georgia", code: "GA" },
  { name: "Hawaii", code: "HI" },
  { name: "Idaho", code: "ID" },
  { name: "Illinois", code: "IL" },
  { name: "Indiana", code: "IN" },
  { name: "Iowa", code: "IA" },
  { name: "Kansas", code: "KS" },
  { name: "Kentucky", code: "KY" },
  { name: "Louisiana", code: "LA" },
  { name: "Maine", code: "ME" },
  { name: "Maryland", code: "MD" },
  { name: "Massachusetts", code: "MA" },
  { name: "Michigan", code: "MI" },
  { name: "Minnesota", code: "MN" },
  { name: "Mississippi", code: "MS" },
  { name: "Missouri", code: "MO" },
  { name: "Montana", code: "MT" },
  { name: "Nebraska", code: "NE" },
  { name: "Nevada", code: "NV" },
  { name: "New Hampshire", code: "NH" },
  { name: "New Jersey", code: "NJ" },
  { name: "New Mexico", code: "NM" },
  { name: "New York", code: "NY" },
  { name: "North Carolina", code: "NC" },
  { name: "North Dakota", code: "ND" },
  { name: "Ohio", code: "OH" },
  { name: "Oklahoma", code: "OK" },
  { name: "Oregon", code: "OR" },
  { name: "Pennsylvania", code: "PA" },
  { name: "Rhode Island", code: "RI" },
  { name: "South Carolina", code: "SC" },
  { name: "South Dakota", code: "SD" },
  { name: "Tennessee", code: "TN" },
  { name: "Texas", code: "TX" },
  { name: "Utah", code: "UT" },
  { name: "Vermont", code: "VT" },
  { name: "Virgin Island", code: "VI" },
  { name: "Virginia", code: "VA" },
  { name: "Washington", code: "WA" },
  { name: "West Virginia", code: "WV" },
  { name: "Wisconsin", code: "WI" },
  { name: "Wyoming", code: "WY" },
];
